# Generated by Django 5.2.1 on 2025-05-31 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_skipkeyword_created_at_skipkeyword_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPromptRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_text', models.CharField(help_text='觸發詞，例如：我想學英文', max_length=255, unique=True)),
                ('system_prompt', models.TextField(help_text='對應的 system prompt 內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_prompts', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
        ),
    ]
