# Generated by Django 5.2.1 on 2025-05-31 18:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_systempromptrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
