# Generated by Django 5.2.1 on 2025-05-31 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_message_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_prompt_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.systempromptrule'),
        ),
    ]
