# Generated by Django 5.2.1 on 2025-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_message_system_prompt_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', '中文')], default='zh', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
